spring.application.name=financePersonal

# =========================
# DATASOURCE (PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_app
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.security.user.name=admin
spring.security.user.password=admin123

app.jwt.secret=dev-secret-12345678901234567890123456789012
app.jwt.issuer=finance-personal-api
app.jwt.expiration-minutes=60